### PR TITLE
Spotify support

### PR DESCRIPTION
**Pull request by felipevieira**

### CODE REVIEW

**Comment by Arcaena** [comment]
I'll look into merging this this weekend; I'll need to redo the regex (lastfm usernames can't have an underscore or hyphen in the first character, apparently spotify can?), and probably tweak the database to allow for different things to watch (lastfm, spotify, librefm) 

Does spotify not require an api key?

**Comment by felipevieira** [comment]
I have some adjustments to make in this PR (I've sent it by accident) so it's ok to wait a few days until looking into it. About the lastfm regex, I suppose they do allow the underscore on the first character (http://www.last.fm/pt/user/_leno), but I'm not so sure about spotify. 

Spotify search api endpoint apparently does not require api key (https://api.spotify.com/v1/search?query=New%20Years%20Day&offset=0&limit=20&type=track)

**Comment by Arcaena** [comment]
Weird, I'd tried making a lastfm account with an underscore for the first character and it says that accounts should start with a letter or number (and it rejects "_testacc", for example), so it appears that there's just some old accounts that start with that, oddly enough. I'll check out spotify's username requirements at some point; I've got finals next week so I'm kinda just dead currently.

Good that spotify requires no key since that makes it easier to implement (or at least, less work on my bots lol)

Tell me whenever you're done with stuff and I'll take a look and probably merge then.

**Comment by felipevieira** [comment]
will do
by the way, the current version of the bot is up and running on a group I'm in :)

snapshot11

**Comment by Arcaena** [comment]
Oh man, spotify even has the album art show for link previews; I really wish lastfm would do that in the song links, but they don't :/

I might do a bit of maintenance on my bot in a bit (telegram appears to have changed part of the messageEntity type thing to now say that messages starting with a / are of the type 'bot_command', which broke some of my bots a bit, aargh)

I really need to redo my other bots somewhat at some point

**Comment by felipevieira** [comment]
Have you checked this https://telegram.org/blog/botprize?

**Comment by Arcaena** [comment]
Yeah, I've seen it, but I don't really think any of my bots are quite ready for that. I still need to get around to doing an inline @emojibot for inserting emoji into text or something, but finals are kinda killing my work on projects.

**Comment by felipevieira** [comment]
you're now good to go on this pull request. let me know if you have any questions

**Comment by Arcaena** [comment]
Thanks! I'll get around to polishing this a bit more (and maybe refactoring my code some, now) some time at the end of this week or something, but many thanks!

**Pull request merged**
